language: go
go:
  - "1.11"

jobs:
  include:
    - stage: build
      script:
        - make build
      after_script:
        - make clean

    - stage: build image
      services:
        - docker
      script:
        - ./build_image.sh bombergame/profiles-service
      after_success:
        - if [[ ${TRAVIS_BRANCH} == "master" ]] && [[ ${TRAVIS_PULL_REQUEST} == "false" ]]; then
            ./push_image.sh bombergame/profiles-service;
          fi

    - stage: deploy
      services:
        - docker
      script:
        - if [[ ${TRAVIS_BRANCH} == "master" ]] && [[ ${TRAVIS_PULL_REQUEST} == "false" ]]; then
            ./deploy.sh;
          fi
