required = [
  "github.com/golang/protobuf/protoc-gen-go",
  "golang.org/x/tools/cmd/cover",
  "github.com/mattn/goveralls"
]

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.7.2"

[[constraint]]
  name = "github.com/gorilla/handlers"
  version = "1.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/bombergame/common"
