// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package rest

import (
	"github.com/mailru/easyjson/jlexer"
	"github.com/mailru/easyjson/jwriter"
)

func (NewProfileData) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*NewProfileData) UnmarshalJSON([]byte) error        { return nil }
func (NewProfileData) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*NewProfileData) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_NewProfileData *NewProfileData

func (ProfileDataUpdate) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*ProfileDataUpdate) UnmarshalJSON([]byte) error        { return nil }
func (ProfileDataUpdate) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*ProfileDataUpdate) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ProfileDataUpdate *ProfileDataUpdate
